# Generated by Django 5.1 on 2024-08-15 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
