# Generated by Django 5.1 on 2024-08-17 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0002_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
